# Generated by Django 5.1.7 on 2025-03-23 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='catgegory',
            new_name='category',
        ),
    ]
